version: v2.3.0

serve:
  public:
    host: 0.0.0.0
    port: 4444
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
  admin:
    host: 0.0.0.0
    port: 4445

oauth2:
  expose_internal_errors: true

log:
  level: debug
  format: json
  leak_sensitive_values: false
