"""name=verify-clean

Revision ID: 762efb267d62
Revises: 940fffd1ff54
Create Date: 2026-03-30 11:51:43.365559

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '762efb267d62'
down_revision: str | Sequence[str] | None = '940fffd1ff54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
