from typing import Protocol

from app.core.oauth2.entities.challenge import ConsentChallenge, LoginChallenge, LogoutChallenge


class OAuth2ChallengeProvider(Protocol):
    async def get_login_challenge(self, challenge: str) -> LoginChallenge: ...
    async def accept_login(self, challenge: str, subject: str, remember: bool) -> str: ...
    async def reject_login(self, challenge: str, error: str, description: str) -> str: ...
    async def get_consent_challenge(self, challenge: str) -> ConsentChallenge: ...
    async def accept_consent(
        self, challenge: str, granted_scope: list[str], subject: str
    ) -> str: ...
    async def reject_consent(self, challenge: str, error: str, description: str) -> str: ...
    async def get_logout_challenge(self, challenge: str) -> LogoutChallenge: ...
    async def accept_logout(self, challenge: str) -> str: ...
